In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree
from sklearn.preprocessing import StandardScaler

In [18]:
dataset = pd.read_csv(r'D:\HopeAI\Training\Week9-ML and Data Science Capstone\1. Data Collection\real_estate_dataset.csv')
dataset

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1.0,3.0,3.0,1967.0,1.0,1.0,48.0,8.297631,5.935734,602134.816747
1,2,287.678577,1.0,2.0,1.0,1949.0,0.0,1.0,37.0,6.061466,10.827392,591425.135386
2,3,232.998485,1.0,3.0,2.0,1923.0,1.0,0.0,14.0,2.911442,6.904599,464478.696880
3,4,199.664621,5.0,2.0,2.0,1918.0,0.0,0.0,17.0,2.070949,8.284019,583105.655996
4,5,89.004660,4.0,3.0,3.0,1999.0,1.0,0.0,34.0,1.523278,14.648277,619879.142523
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,NaN,2.0,2.0,2.0,1967.0,1.0,0.0,16.0,4.296086,5.562583,488496.350722
496,497,195.914028,2.0,3.0,1.0,1977.0,0.0,1.0,45.0,7.406261,2.845105,657736.921717
497,498,69.433659,1.0,1.0,2.0,2004.0,0.0,0.0,18.0,8.629724,6.263264,405324.950201
498,499,293.598702,NaN,1.0,3.0,1940.0,NaN,0.0,41.0,5.318891,16.990684,773035.968028
499,500,296.552686,4.0,3.0,1.0,1988.0,1.0,1.0,20.0,7.894322,1.779794,864299.500218

# Data Preprocessing

In [19]:
#Detect missing values

dataset.isnull().sum()

ID                     0
Square_Feet           25
Num_Bedrooms          25
Num_Bathrooms         25
Num_Floors            25
Year_Built            25
Has_Garden            25
Has_Pool              25
Garage_Size           25
Location_Score        25
Distance_to_Center    25
Price                 25
dtype: int64

In [20]:
#Handle missing values

dataset.dropna()

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1.0,3.0,3.0,1967.0,1.0,1.0,48.0,8.297631,5.935734,602134.816747
1,2,287.678577,1.0,2.0,1.0,1949.0,0.0,1.0,37.0,6.061466,10.827392,591425.135386
2,3,232.998485,1.0,3.0,2.0,1923.0,1.0,0.0,14.0,2.911442,6.904599,464478.696880
3,4,199.664621,5.0,2.0,2.0,1918.0,0.0,0.0,17.0,2.070949,8.284019,583105.655996
4,5,89.004660,4.0,3.0,3.0,1999.0,1.0,0.0,34.0,1.523278,14.648277,619879.142523
...,...,...,...,...,...,...,...,...,...,...,...,...
492,493,119.345296,4.0,3.0,2.0,1966.0,1.0,0.0,25.0,7.219292,6.937720,619610.370076
493,494,97.030290,5.0,1.0,1.0,1948.0,0.0,0.0,45.0,3.848036,8.712896,492310.608883
496,497,195.914028,2.0,3.0,1.0,1977.0,0.0,1.0,45.0,7.406261,2.845105,657736.921717
497,498,69.433659,1.0,1.0,2.0,2004.0,0.0,0.0,18.0,8.629724,6.263264,405324.950201
499,500,296.552686,4.0,3.0,1.0,1988.0,1.0,1.0,20.0,7.894322,1.779794,864299.500218

In [21]:
# Fill with mean
dataset.fillna(dataset.mean())

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1.000000,3.0,3.0,1967.0,1.000000,1.0,48.0,8.297631,5.935734,602134.816747
1,2,287.678577,1.000000,2.0,1.0,1949.0,0.000000,1.0,37.0,6.061466,10.827392,591425.135386
2,3,232.998485,1.000000,3.0,2.0,1923.0,1.000000,0.0,14.0,2.911442,6.904599,464478.696880
3,4,199.664621,5.000000,2.0,2.0,1918.0,0.000000,0.0,17.0,2.070949,8.284019,583105.655996
4,5,89.004660,4.000000,3.0,3.0,1999.0,1.000000,0.0,34.0,1.523278,14.648277,619879.142523
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,175.054030,2.000000,2.0,2.0,1967.0,1.000000,0.0,16.0,4.296086,5.562583,488496.350722
496,497,195.914028,2.000000,3.0,1.0,1977.0,0.000000,1.0,45.0,7.406261,2.845105,657736.921717
497,498,69.433659,1.000000,1.0,2.0,2004.0,0.000000,0.0,18.0,8.629724,6.263264,405324.950201
498,499,293.598702,2.968421,1.0,3.0,1940.0,0.528421,0.0,41.0,5.318891,16.990684,773035.968028
499,500,296.552686,4.000000,3.0,1.0,1988.0,1.000000,1.0,20.0,7.894322,1.779794,864299.500218

In [22]:
# Fill with median
dataset['Square_Feet'].fillna(dataset['Square_Feet'].mean(), inplace=True)

In [16]:
dataset

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1.0,3.0,3.0,1967.0,1.0,1.0,48.0,8.297631,5.935734,602134.816747
1,2,287.678577,1.0,2.0,1.0,1949.0,0.0,1.0,37.0,6.061466,10.827392,591425.135386
2,3,232.998485,1.0,3.0,2.0,1923.0,1.0,0.0,14.0,2.911442,6.904599,464478.696880
3,4,199.664621,5.0,2.0,2.0,1918.0,0.0,0.0,17.0,2.070949,8.284019,583105.655996
4,5,89.004660,4.0,3.0,3.0,1999.0,1.0,0.0,34.0,1.523278,14.648277,619879.142523
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,175.054030,2.0,2.0,2.0,1967.0,1.0,0.0,16.0,4.296086,5.562583,488496.350722
496,497,195.914028,2.0,3.0,1.0,1977.0,0.0,1.0,45.0,7.406261,2.845105,657736.921717
497,498,69.433659,1.0,1.0,2.0,2004.0,0.0,0.0,18.0,8.629724,6.263264,405324.950201
498,499,293.598702,NaN,1.0,3.0,1940.0,NaN,0.0,41.0,5.318891,16.990684,773035.968028
499,500,296.552686,4.0,3.0,1.0,1988.0,1.0,1.0,20.0,7.894322,1.779794,864299.500218